FROM golang:1.24-alpine

RUN apk add --no-cache git ca-certificates tzdata

WORKDIR /app

# Install air
RUN go install github.com/air-verse/air@v1.52.3

# Copy go mod dulu (cache dependency)
COPY go.mod go.sum ./
RUN go mod download

# Copy semua source
COPY . .

EXPOSE 8090 9002

CMD ["air"]