-- +goose Up
-- +goose StatementBegin

SET search_path TO orbguard_lab, public;

-- DNS leak-check canary queries observed by the authoritative canary
-- responder (cmd/dnscanary). Every A/AAAA query for {token}.$CANARY_ZONE
-- that reaches the authoritative server is recorded here; the API's
-- POST /network/dns/check leak section looks up the client's token to learn
-- which resolver IP actually performed the lookup on the device's behalf.
--
-- Rows are write-once observations; the canary daemon only INSERTs and the
-- API only SELECTs by token. resolver_asn is nullable: it is populated only
-- if/when an ASN enrichment source is wired in — it is never guessed.
CREATE TABLE orbguard_lab.dns_canary_queries (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Random token generated by the client (leftmost DNS label of the
    -- canary qname). Lowercase hex/base32-safe charset, 8..63 chars.
    token VARCHAR(63) NOT NULL,

    -- Source address of the resolver that sent the query to the
    -- authoritative canary server (i.e. the egress IP of whichever recursive
    -- resolver actually handled the device's lookup).
    resolver_ip INET NOT NULL,

    -- Autonomous system number of resolver_ip, when enrichment is available.
    resolver_asn INTEGER,

    -- DNS query type as text ("A", "AAAA") and transport ("udp", "tcp").
    qtype VARCHAR(10) NOT NULL DEFAULT 'A',
    transport VARCHAR(3) NOT NULL DEFAULT 'udp',

    queried_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_dns_canary_queries_token ON orbguard_lab.dns_canary_queries(token);
CREATE INDEX idx_dns_canary_queries_queried_at ON orbguard_lab.dns_canary_queries(queried_at);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

SET search_path TO orbguard_lab, public;

DROP TABLE IF EXISTS orbguard_lab.dns_canary_queries;

-- +goose StatementEnd
